if !(isServer) exitWith {};
clearmagazinecargoglobal _this;
clearweaponcargoglobal _this;
clearitemcargoglobal _this;
clearbackpackcargoglobal _this;
_this allowDamage false;
sleep 5;
if(!((profileNameSpace getVariable ["#AUSMD#Boxes",[]]) isEqualTo [])) exitWith {};
_this addweaponcargoglobal ["arifle_MXC_Black_F", 6];
_this addmagazinecargoglobal ["30Rnd_65x39_caseless_mag", 200];
_this addweaponcargoglobal ["Binocular", 6];
_this additemcargoglobal ["ItemGPS", 6];
_this additemcargoglobal ["optic_Aco", 6];
_this additemcargoglobal ["acc_flashlight", 6];
_this addmagazinecargoglobal ["SmokeShell", 12];
_this addmagazinecargoglobal ["SmokeShellRed", 12];
_this addmagazinecargoglobal ["SmokeShellPurple", 12];
_this addmagazinecargoglobal ["Chemlight_Yellow", 12];
_this addmagazinecargoglobal ["Chemlight_Red", 12];